spring.datasource.url=jdbc:postgresql://dpg-d6b9tm0boq4c73fgsfhg-a:5432/bweb_db_qftg
spring.datasource.username=bweb_db_qftg_user
spring.datasource.password=cLly5QKQ7iAwhNR0hCgRkwqz7EgCB6Iv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


CLOUDINARY_CLOUD_NAME=dllgywkvy
CLOUDINARY_API_KEY=793392597185934
CLOUDINARY_API_SECRET=mqYJOvYqjnozwPms3Vv9kM9zbBI

spring.main.lazy-initialization=true
