spring.datasource.url=jdbc:postgresql://dpg-d6b9tm0boq4c73fgsfhg-a:5432/bweb-db
spring.datasource.username=bweb_db_qftg_user
spring.datasource.password=cLly5QKQ7iAwhNR0hCgRkwqz7EgCB6Iv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.main.lazy-initialization=true
